---
abstract: 'Yet another BDD testing library(Development Release)'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Ika
no_index:
  directory:
    - inc
provides:
  Test::Ika:
    file: lib/Test/Ika.pm
    version: 0.02
  Test::Ika::Example:
    file: lib/Test/Ika/Example.pm
    version: 0
  Test::Ika::ExampleGroup:
    file: lib/Test/Ika/ExampleGroup.pm
    version: 0
  Test::Ika::Reporter::Spec:
    file: lib/Test/Ika/Reporter/Spec.pm
    version: 0
  Test::Ika::Reporter::TAP:
    file: lib/Test/Ika/Reporter/TAP.pm
    version: 0
  Test::Ika::Reporter::Test:
    file: lib/Test/Ika/Reporter/Test.pm
    version: 0
requires:
  Exporter: 0
  Module::Load: 0
  Scope::Guard: 0
  Term::Encoding: 0
  Test::More: 0.98
  Test::Name::FromLine: 0.06
  Try::Tiny: 0
  parent: 0
  perl: 5.010001
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
